### ISSUE TITLE
Search non-existing keys in P-Masstree

### ISSUE THREAD

**Issue by Transpeptidase** [utsaslab/RECIPE#15]
Hi, when I  invoke a `get` for non-existing keys in P-Masstree,  "should not enter here....." is printed.

code:
```c
  masstree::masstree *tree = new masstree::masstree();
  auto t = tree->getThreadInfo();
  char *str = "helloworld";
  tree->get(str, t);
```

printed information:
```
should not enter here
fkey = rowolleh, key = 7522537965574647666, searched key = 0, key index = -1
```

**Comment by SeKwonLee** [comment]
Hi @Transpeptidase ,

That context printing "should not enter here.." was added for the debugging purpose to check if the positive search operations enter there. So, if you see "should not enter here..." after the negative search, it means the algorithm that I intended works correctly. I have commented out that context not to show debugging messages through [the recent commit](https://github.com/utsaslab/RECIPE/commit/2382d2f36d217e9282ca2b4cfb4446eec5c2ef14) to the master branch. Please do git pull once.

Thanks,
Sekwon

**Comment by SeKwonLee** [comment]
Let me close this issue. Please open another issue if you find others.
