### ISSUE TITLE
FAST_FAIR Range Bug

### ISSUE THREAD

**Issue by Transpeptidase** [utsaslab/RECIPE#16]
In ``linear_search_range`` of /third-party/FAST_FAIR/btree.h, ``count()`` should be ``current->count()``,

**Comment by SeKwonLee** [comment]
I think it is not a bug. count() function called in linear_search_range is this->count() that is equivalent current->count() (page *current = this in line 1041 and 1132). Could you check it once more? Please let me know if I missed something.

**Comment by Transpeptidase** [comment]
``current`` may be not equivalent to ``this``, since ``current`` is changed when the thread follows sibling pointers.
see line 1120
``` c
if (snapshot_n == current->hdr.sibling_ptr)
  current = current->hdr.sibling_ptr;
else
  off = old_off;
```

**Comment by SeKwonLee** [comment]
Make sense. Thanks for the report. Could you make a pull request to fix that bug?

**Comment by Transpeptidase** [comment]
ok
