### ISSUE TITLE
Crash-consistency bug in P-CLHT `clht_gc_collect_cond`

### ISSUE THREAD

**Issue by task3r** [utsaslab/RECIPE#24]
The value of `hashtable->ht_oldest` is not persisted after the free, meaning that a post-crash execution can read the previous value and perform a double-free.
https://github.com/utsaslab/RECIPE/blob/05a49d7649d7549f6a15b604c1b67c5208977770/P-CLHT/src/clht_gc.c#L183-L196

**Comment by SeKwonLee** [comment]
That depends how you implement post-crash mechanisms before we resume threads after a crash to the index. Although we don't provide detailed post-crash mechanisms, what if we make the post-crash mechanisms set entries in `clht_t` to the initialized values (e.g. ht_oldest = NULL) before returning it to threads? In this case, double-free will not happen, but memory leak may occur. However, as we assume GC-supported memory allocator, the old hash table should be reclaimed by the allocator eventually. Please let me know how you think.

**Comment by task3r** [comment]
Thank you for the quick response. I believe that you are right, if those mechanisms were in place this would not be an issue.
